spring:
  ai:
    mcp:
      server:
        name: my-image-search-mcp-server
        version: 1.0.0
        type: SYNC
        # stdio
        stdio: true
  # stdio
  main:
    web-application-type: none
    banner-mode: off